[package]
name = "tinymd"
version = "0.1.2"
authors = ["James Hawley <developer@jrhawley.ca>"]
homepage = "https://github.com/jrhawley/tinymd"
description = "A small Markdown parser written in Rust"
edition = "2021"

[dependencies]
clap = { version = "3", features = ["cargo"] }
regex = "1"
